VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Node"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' Class: Node
' Used to construct blockchain objects

' ------------------
'  Member Variables
' ------------------

' write code here


' ------------------
'    Properties
' ------------------

' write code here


' ------------------
'     Events
' ------------------
Private Sub Class_Initialize()

' Constructor

End Sub

Private Sub Class_Terminate()

' Destructor

End Sub


' ------------------
'     Methods
' ------------------

' write code here
